server:
  port: 8082
  servlet:
    session:
      timeout: 15m
      cookie:
        http-only: true
        secure: true

spring:
  application:
    name: hostel-order

  datasource:
    url: jdbc:postgresql://localhost:5432/hostel-order
    username: postgres
    password: shushkevich

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true

    show-sql: false
